### ISSUE TITLE
Make sure WFC3 tests delete trailer files before running

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#216]
@jhunkeler alerted me to some `.tra` files that are 20GB in size and appears to be appending log since 2015. The solution is to comb through WFC3 test scripts and ensure that they remove `rootname.tra` along with other outputs from previous run before the line of code that executes HSTCAL.

p.s. Don't use `*.tra` with the wildcard, as that would mess up other tests that might be running in parallel.

**Comment by mdlpstsci** [comment]
Are the test scripts in the repository (github), or are they only on nott and pembry?

**Comment by pllim** [comment]
Not on GitHub

**Comment by mdlpstsci** [comment]
I have updated the appropriate WFC3 scripts to remove the offending *.tra files before the processing of new data.  Since it was only the *.tra associated with the association table which was not being removed, I only appended or extended the current Python list to include the appropriate file name.  Here is an example,

    tempfiles.extend(['iaao01010.tra','iaao01011.tra'])

This has been verified to be working correctly now.  The modified scripts have been committed to SVN from one test area as the Pandokia system looks for and checks out updated scripts from SVN and installs the updated scripts into any stale test areas as necessary.  I have checked all four test areas, and all the *.tra files are fresh (not appended) and from the latest test run.

**Comment by jamienoss** [comment]
@mdlpstsci which test was this or were there multiple?
