### ISSUE TITLE
CALSTIS failure

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#298]
Truth appears to be missing:

https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=134863803

**Comment by stscirij** [comment]
No it looks like a fail in the run

ERROR    Output file `out/TEMPX1D_calstis_lev1_FUVspec_x1d.fits' already exists.
calstis0 failed.

**Comment by stscirij** [comment]
I removed the TEMP files from the out/ directory, the test should run OK now

**Comment by jamienoss** [comment]
It may be due to all the recent killing and restarting of tests for 2018.1. A similar situation was found with a previous WFC3 test. There is no easy bulk cleanup procedure for the suite (that I am aware of). We could look at the test in question and see if this file is in the test's pre-run rm list. If it is not and pandokia was killed before this test completed then this temp file would not be removed. I am assuming that this is a tmp file due to the 'TEMP" prefix.

**Comment by stscirij** [comment]
It's not in the pre-exec steps.  We should definitely put in some lines to remove the TEMP files that could be created.  I'll do that.

**Comment by pllim** [comment]
Thanks for the quick fix!
