### ISSUE TITLE
ACSREJ: ERR extension is computed, rather than propagated

### ISSUE THREAD

**Issue by nmiles2718** [spacetelescope/hstcal#371]
In the process of reviewing some previous updates regarding the treatment of error by the `ACSREJ `algorithm, I realized that the errors aren't being propagated. Instead at the end of the combination process, the errors are computed based off a model for what they should look like. While this isn't a bad approximation, it is incorrect and will wipeout contributions from the superbias. 

As a test case, I took two `FLT` images and replaced their ERR arrays with all 0's. I then combined those two images using `acstools` to create jd5702091_no_err_crj.fits and then examined the output SCI and ERR extension. If `ACSREJ` were propagating the error from the input images, then you would expect the final ERR extension of the combined product to be all zeros. In the figure below, you can see that this is not the case.
![example](https://user-images.githubusercontent.com/20194427/47730110-e2222280-dc37-11e8-98a1-fe307681242a.png)

**Comment by pllim** [comment]
Might want to bring @nagrogin into this discussions. He had a lot of say of the ACSREJ refactoring although I really don't remember if this thingy already happening *before* my PR.

**Comment by mdlpstsci** [comment]
Hi,
He is already in the discussion. This was done to formally record the issue.

Best,
Michele

Michele D. De La Pena
Space Telescope Science Institute
mdelapena@stsci.edu<mailto:mdelapena@stsci.edu>
Mobile: 520.419.8825
Office: 667.218.6501

**Comment by mdlpstsci** [comment]
What equation does the team want me to use for the computation?  I could add the uncertainties in quadrature (i.e., dq = sqrt[ (d1)^2 + (d2)^2 + (d3)^2 + ... (dn)^2) ] where d# is err = f(image#, x, y) and the pixels which were not actually used to compute the final image would not be included.  @nmiles2718

**Comment by pllim** [comment]
Equation to compute ERR should already be in DHB. If that is changing, ACS Team needs to update it there as well. FYI.

**Comment by nmiles2718** [comment]
The equation will be changed and the DHB will be updated accordingly. It's been a while since this issue was submitted and I need to review my notes and talk with Norman to make sure we're on the same page wrt to the new equation. At first glance, the equation you are listing @mdlpstsci is along the lines of what we want, but I'll get back to you soon with a more rigorous answer.

**Comment by mdlpstsci** [comment]
@jryon 
An updated version of CALACS is available for you to test on the Linux
servers (I used plhstins4).  The summary of the changes are:

### 11-Jan-2022 - MDD - Version 10.3.4
    Update to the cosmic ray rejection algorithm as to the way
    the output ERR extension is computed for the CRJ file. The
    output ERR is now propagated from the usable input ERR extensions
    versus being computed by a model.

    Fixed a bug which was triggered ONLY when executing the condaforge
    distribution on MacOS where failure was due to a missing return
    statement.  Only call computeDarktime() once to compute the updated
    DARKTIME primary keyword and function return is now void. Update
    the keyword in main to avoid passing extra data by reference.

Please note the "bug" fix was done to accommodate our "soon to be" new
build system which revealed an issue.  This modification did not change
any output data.  The update of interest to you is the "acsrej".  The
update has been implemented as described in Git Issue #371.

To answer your related questions...
If a pixel is associated with a cosmic ray in every input image,
- SCI is basically the sum of the sky values computed for each input
  image by acsrej_sky.c.
- ERR is zero (in the crj_tmp.fits file), and
- DQ is 8192 (plus any other flag it might also have).

After ACSREJ is done, ACS2D is executed and the various corrections can 
modify the values of the "CR" pixels a bit in the creation of the final
crj.fits file (or at least this is what I observed in my test data). In 
my test cases,
- SCI values were very modestly changed, 
- ERR were no longer zero (e.g., 0.23),
- DQ were the same.
I will have to check all the ACS2D corrections to see how the
crj_tmp DQ is accommodated.

The executable should be invoked on your data of choice as follows:

/home/mdelapena/repos/hstcal/bin.Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17/calacs.e 

If you have any issues with the software, please do NOT hestitate
to contact me.
Best,
Michele

**Comment by jryon** [comment]
Thanks, @mdlpstsci ! Do you think testing the acsrej.e executable in that directory would be good enough? I was going to create a few test files with all zeros and all ones in the ERR array (so it's easy to check for correct propagation), but using calacs.e requires starting from RAWs, which do not have ERR arrays.

**Comment by mdlpstsci** [comment]
@jryon Your plan is sound since you will control the inputs.  All the "other" acs executables are also located in the same directory, so you can use `acsrej.e` directly.

**Comment by jryon** [comment]
@mdlpstsci  I've done some initial testing with `acsrej.e` and have a couple of questions.

1. When I set the ERR arrays of two BLV_TMP files to zero and run acsrej.e on them, the resulting CRJ does not have ERR arrays at all:

> (astroconda) ryon@warbler:/grp/hst/acs3/ryon/test_acsrej/check_bugfix$ fitsinfo err0_test
Filename: err0_test
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     246   ()      
  1  SCI           1 ImageHDU        95   (4096, 2048)   float32   
  2  ERR           1 ImageHDU        49   ()      
  3  DQ            1 ImageHDU        40   (4096, 2048)   int16   
  4  SCI           2 ImageHDU        95   (4096, 2048)   float32   
  5  ERR           2 ImageHDU        49   ()      
  6  DQ            2 ImageHDU        40   (4096, 2048)   int16   

Is this expected? I suppose there's no real-world impact of this, but I would have assumed the CRJ ERR arrays would still be present, just all zeros.

2. When I set the ERR arrays of the same two BLV_TMP files to 1 and process them with `acsrej.e`, I see that many more pixels are flagged as CRs than in the original BLV_TMP files processed with `acsrej.e`. So, it seems like the ERR arrays are used somewhere in the CR rejection algorithm, which I'm not sure I expected. Is that behavior correct?

Otherwise, the propagation in the ERR = 1 case looks correct to me. I will run calacs.e on a "natural" dataset as you suggest, and let you know how it looks. Thanks!

**Comment by jryon** [comment]
The "natural" dataset ERR propagation looks correct as well.

**Comment by mdlpstsci** [comment]
@jryon 
For your Item 1, if the resultant CRJ ERR is expected to be all zeros (or all pixels contain the same value), then what you are seeing is a space efficiency issue.  I cannot remember if this part of the FITS standard or an STScI convention (think it may just be an STScI convention), but if every pixel in an image has the same value, the image does not exist in a 2D form.  Instead, it is represented by FITS keywords (NPIX1, NPIX2, PIXVALUE - If I remember the keywords correctly) in the extension.  Please check for these keywords.  Also, please put the file somewhere I can examine it.

As for Item 2
The data in the ERR image is used to compute the thresholds and "spill" thresholds against which CRs are detected.  

As an important aside, this means the equation in section 3.4.3 for 𝜏𝑛 is out of date since January 2016 when a change was made to use ERR as a factor instead of the (noise +  pix/gain).

Current Equation in handbook
𝜏𝑛=𝜎^2(noise + pix(𝑥,𝑦) /gain + scale(pix(𝑥,𝑦)−sky𝑛)^2) / 𝑇𝑛^2

The equation is coded as
𝜏𝑛 = 𝜎2 * (ERR^2 + [scale * (pix(𝑥,𝑦) * efac𝑛)]^2) / 𝑇𝑛^2
where ERR is in electrons, 
pix(x,y) is sky subtracted and in units of elections/s,
efac𝑛 is the exposure time of the image in s

**Comment by mdlpstsci** [comment]
@jryon I can put an value somewhere on the edge of the ERR image to force an actual image to be created.  This is often done, so it is not a "special case" of anything.  I probably should have done this as users can be confused about the "missing" images.  I will let you know what updated software is available (later this week).

**Comment by jryon** [comment]
@mdlpstsci sounds good, thanks!

One quick question about the new equation for 3.4.3. You say that _efacn_ is the exposure time of the image in seconds - isn't that what _Tn_ is?

**Comment by mdlpstsci** [comment]
@jryon
Yes, efacn is Tn.

**Comment by mdlpstsci** [comment]
@jryon 
I have put a new version of the software on the Linux servers for you to test.  The only change made was to force the ERR extension to have an actual two-dimensional image.  Again, you can access the actual binary as:

/home/mdelapena/repos/hstcal/bin.Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17/calacs.e yourTestFileHere.fits

**Comment by jryon** [comment]
@mdlpstsci Working on it now, should be done today.

**Comment by jryon** [comment]
@mdlpstsci Looks good. I approve this software update. Thank you!
