### ISSUE TITLE
Consolidate stiserr.h, wf3err.h, & acserr.h to hstcal/include/err.h

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#95]

**Comment by pllim** [comment]
Are they all absolutely the same? If things are not broken, don't fix it?

**Comment by stsci-hack** [comment]
Since this issue does not affect science data (or any array), there should be no reason to hold this change.  This change should be integrated into HSTCAL as an infrastructure issue not related to the instruments, but rather to how the code works.  This is not a matter of whether it was broken or not, since it was bad design that should have been integrated when we merged all the instrument's code into HSTCAL in the first place to make it more understandable and maintainable.
